name: Create dummy repo commits so scheduled jobs aren't disabled after 60 days of repo inactivity
on:
  workflow_dispatch:
  schedule:
    - cron:  '37 04 26 1,3,5,7,9,11 *'
jobs:
  dummy-keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Dummy keepalive commit
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit --allow-empty -am "Dummy keepalive commit"
          git push
